### ISSUE TITLE
E Publication downloads produce a 403 forbidden error when clicked

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/classic#109]
All of the links on E Pub download page show 403 forbidden when clicked.

![sirenia epubs](https://user-images.githubusercontent.com/19557452/34735231-bfa05d5e-f53c-11e7-9a95-a355c1235812.jpeg)

**Comment by jpjenk** [comment]
Fixed in commit 02c0bdc. File creation mask was set incorrectly and not in the right places for the production server ruid. For future reference, umask takes an octal number not a string to represent the posix mode bits. For safety only read bits are now set for scratch files. The fact that this worked in the testing environment is a fluke. This has also been corrected and all scratch paths have been sanitized across systems.
