### ISSUE TITLE
Eco/Taph form selectively saves updated info

### ISSUE THREAD

**Issue by jocsessa** [paleobiodb/classic#120]
I am updating the ecological characteristics of various mollusks, and am unable to change/update the "life habitat" of certain taxa, but am able to change it for other taxa.  I have been unable to update "Polinices" and "Euspira" which are both in the "Naticidae", from "infaunal" to "semi-infaunal"; however Mark Uhen was able to update both of these.  I am still unable to update "Natica" which is in this family.  I have been able to update several taxa, such as "Epitonium" and "Nassarius" - neither of which are in the Naticidae.  After trying to make the change, I always receive the message "Ecological/taphonomic data for Natica have been updated". but the change is not displayed when I search for the taxon. It seems to only be a problem for updating genera within the Naticidae that were originally designated as "infaunal".

**Comment by mmcclenn** [comment]
The cause of this problem was that the system does not allow people to update non-empty fields in records that they do not own, except in certain tables. I added 'ecotaph' to the set of tables for which anybody can update records.

**Comment by mmcclenn** [comment]
Hi Jocelyn,

I just fixed this. This was, essentially, a policy problem rather than a bug in the code. Some database tables allow anybody to update records, while others allow only the person who created a record (or a super-user, which Mark is) to edit non-empty fields. I added ‘ecotaph’ to the list of tables in which anybody can enter records.

  — Michael

On Mar 19, 2018, at 1:32 PM, jocsessa <notifications@github.com<mailto:notifications@github.com>> wrote:


I am updating the ecological characteristics of various mollusks, and am unable to change/update the "life habitat" of certain taxa, but am able to change it for other taxa. I have been unable to update "Polinices" and "Euspira" which are both in the "Naticidae", from "infaunal" to "semi-infaunal"; however Mark Uhen was able to update both of these. I am still unable to update "Natica" which is in this family. I have been able to update several taxa, such as "Epitonium" and "Nassarius" - neither of which are in the Naticidae. After trying to make the change, I always receive the message "Ecological/taphonomic data for Natica have been updated". but the change is not displayed when I search for the taxon. It seems to only be a problem for updating genera within the Naticidae that were originally designated as "infaunal".
