### ISSUE TITLE
New Taxon info page features

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/classic#128]
1. Add indication of whether GeoDeepDive literature is already entered into PBDB.
2. Add iDigBio link to specimen associated with each picture.

**Comment by mclapham** [comment]
When there is no literature obtained in the search, the page only displays "Loading..." rather than reporting no results.

**Comment by mmcclenn** [comment]
Can you tell me which taxon you used?

On Aug 28, 2018, at 5:39 PM, Matthew E. Clapham <notifications@github.com<mailto:notifications@github.com>> wrote:


When there is no literature obtained in the search, the page only displays "Loading..." rather than reporting no results.

**Comment by mclapham** [comment]
I used the genus Xenomorphia as a test, because it was published yesterday. Now it says "ERROR loading information from GeoDeepDive".

**Comment by mmcclenn** [comment]
Fixed. It now properly reports “No results found for <taxon name>”. Thanks for catching this!

  — Michael

On Aug 29, 2018, at 2:38 PM, Matthew E. Clapham <notifications@github.com<mailto:notifications@github.com>> wrote:


I used the genus Xenomorphia as a test, because it was published yesterday. Now it says "ERROR loading information from GeoDeepDive".

**Comment by markuhen** [comment]
On the basic Taxon Info page the View classification link is broken. When you click it, it goes nowhere.
