### ISSUE TITLE
Problem accessing data input forms with Student users

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/classic#186]
I am encountering some site errors while trying to enter data. Should I continue to email you about them? Or is there a dedicated person to deal with these issues. 

When looking for a reference under "Add new reference", if the reference exists, it searches just fine, but if it doesnt I get "cannot open template reference_entry_form." I thought "Maybe ill trick the system by looking for an existing reference and just hit the add reference button at the bottom", but I get the same error.
Also, whenever I hit the main menu button it acts like I have just logged out even though my name still appears in the top right.
![Screen Shot 2021-03-25 at 1 08 35 PM](https://user-images.githubusercontent.com/19557452/112637256-53b82800-8e14-11eb-825b-9766c00fc62e.png)

**Comment by mmcclenn** [comment]
Mark, I figured out what is going on. The first user account that was created for Owen, "owenalfaro", does not have an authorizer assigned. The second one has you assigned as the authorizer. That is what makes the difference.

I am going to put a check into the code so that if somebody tries to log in as an enterer with no assigned authorizer it will display a message saying "You must be assigned an authorizer before you can enter data." That will make it clear what needs to be done.
